# LR - 0.00025, Val metrics, batch - 4, 2 gpus
# Data - Train V5 = 8000, Test  = 1562 , Val = 1008
# mean and std tensor  tensor([0.4566, 0.4344, 0.4014]) tensor([0.2731, 0.2612, 0.2496])
# l, h, w = dims[0], dims[1], dims[2]
# float(row['dl']),  float(row['dh']), float(row['dw']),  
# avg_car:  [ 4.58213498  1.55453479  2.01378767 20.17567102]
# avg_ped: [ 0.39206633  1.70414567  0.39206633 20.10306942]
# avgdep:  20.14019779172293
# stdz: 10.737944730464678

MODEL:
  WEIGHT: "catalog://ImageNetPretrained/DLA34"
  #WEIGHT :  "./tools/logs_v4.2/model_final_100.pth"
  #Make this false during testing and True when training
  VAL: True
INPUT:
  FLIP_PROB_TRAIN: 0.5
  SHIFT_SCALE_PROB_TRAIN: 0.3
  PIXEL_STD : [0.2731, 0.2612, 0.2496]
  PIXEL_MEAN : [0.4566, 0.4344, 0.4014] 
DATASETS:
  DETECT_CLASSES: ("Car", "Cyclist", "Pedestrian")
  TRAIN: ("carla_train",)
  TEST: ("carla_test",)
  VALIDATION: ("carla_val",)
  TRAIN_SPLIT: "train"
  TEST_SPLIT: "test"
  VALIDATION_SPLIT: "val"
  CUSTOM_DATA: True
SOLVER:
  BASE_LR: 0.00025
  STEPS: (35, 70)
  MAX_ITERATION: 70
  IMS_PER_BATCH: 16
OUTPUT_DIR : "./logs/logs_v8.1"